

#Setup qa/stg env options
parameters:
- name: environment
  displayName: 'Test Environment'
  type: string
  default: qa
  values:
    - qa
    - stg

#Everytime there is a commit in master branch pipeline will run automatically
trigger:
- master

pool:
  vmImage: ubuntu-latest

#Set important id and password in variable group
variables:
- group: test_env_variable 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.14'
  displayName: 'Setup Python 3.14'

- script: |
    cd DemoFramework
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd DemoFramework
    python -m playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: |
    cd DemoFramework
    pytest --junitxml=test-results.xml --html=report.html --self-contained-html
  displayName: 'Run Playwright tests'
  env:
    TEST_USERNAME: $(TEST_USERNAME)
    TEST_PASSWORD: $(TEST_PASSWORD)
    TEST_ENVIRONMENT: ${{parameters.environment}}

#PublishTestResult@2 - this task publishes report to Test section of pipeline
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'DemoFramework/test-results.xml'
  displayName: 'Publish JUnit test results'
  condition: succeededOrFailed()

 # Uploads the HTML report so you can download and view it from the build summary
- task: PublishPipelineArtifact@1
  inputs:
     targetPath: '$(System.DefaultWorkingDirectory)/DemoFramework/report.html'
     artifact: 'Playwright-HTML-Report'
     publishLocation: 'pipeline'
  displayName: 'Publish HTML Report Artifact'
  condition: succeededOrFailed()  
    
